# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 技术成就未来 !
name: Andy
email: liyf23@163.com
location: Beijing,China
company: Lenovo
company_url: http://www.gfi.fr/en/
github_url: https://github.com
description: This is personnel website of Andy
favicon: favicon.png # Image must be in assets/images

url: http://1327523532.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: SpringCloud

  -
    href: /blog
    label: Blogs

  -
    href: /bookmark
    label: Link

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++,Python, MySQL,Redis,MongoDB,FastDFS,Mycayt,Design Patterns]
skill_j2ee_keywords: [Springboot,Springcloud,Spring, Struct, Hibernet, MyBatis]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS,, Boostrap]
