# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 风雨无阻
subtitle: 不忘初心，方得始终！ 
name: 风雨无阻
description: This is personnel website of Andy
keywords: Spring,Spring Boot,Spring Cloud,MongoDB,大数据,FastDFS,开发者,Developer,Java,Python
email: liyf23@163.com
location: Beijing,China
company: Cloud
company_url: http://www.gfi.fr/en/
github_url: https://github.com
encoding: "utf-8"
favicon: favicon.jpg # Image must be in assets/images
url: https://1327523532.github.io # the base hostname & protocol for your site

repository: 1327523532.github.io
github_url: https://github.com/1327523532

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 5
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /ai.html
    label: AI

  -
    href: /archives.html
    label: Archives

  -
    href: /timeline.html
    label: Timeline

  -
    href: /open-source.html
    label: Open-Source

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words 按照专题聚合的文章
labels:

  -
    href: /jvm.html
    name: JVM

  -
    href: /blog.html
    name: 推荐

  -
    href: /life.html
    name: 故事

  -
    href: /arch.html
    name: 架构

# selected articles 精选的主题
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 分享人生感悟，记录生活点滴

  -
    href: /arch.html
    name: 架构之路
    describe: 一个架构师的成长历程


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java,Python,C++,Design Patterns,Mysql,Redis,MongoDB,ELK,Kafka,RabbitMQ,Mycat,HaProxy,KeepAlived,Nginx,FastDFS,Hadoop,Hive,Spark]
skill_j2ee_keywords: [Spring, SpringMVC,SpringBoot,SpringCloud,Struct, Hibernet, MyBatis,JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax,Boostrap,Angular,Vue,ReactNative]
skill_mobile_app_keywords: [vuejs]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 1327523532
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 1327523532
    repo: blog-comments
    oauth:
        client_id: ca8b216a26080467edbf
        client_secret: ddca9fa83261d0e801cd1b4d7fc220793760d442
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 1327523532
    repo: blog-comments
    clientID: ca8b216a26080467edbf
    clientSecret: ddca9fa83261d0e801cd1b4d7fc220793760d442
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
